# Generated by Django 4.2.3 on 2025-10-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0012_productrating"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderproduct",
            name="item_status",
            field=models.CharField(
                choices=[
                    ("Ordered", "Ordered"),
                    ("Cancelled", "Cancelled"),
                    ("Returned", "Returned"),
                ],
                default="Ordered",
                max_length=20,
            ),
        ),
    ]
