# Generated by Django 4.2.3 on 2025-10-22 23:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0013_orderproduct_item_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderproduct",
            name="refunded",
            field=models.BooleanField(default=False),
        ),
    ]
