# Generated by Django 4.2.3 on 2025-10-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0014_orderproduct_refunded"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="refund_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="refund_status",
            field=models.CharField(
                choices=[
                    ("none", "No Refund"),
                    ("partial", "Partial Refund"),
                    ("full", "Full Refund"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
