# Generated by Django 5.0 on 2024-02-12 06:24

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizestockcount',
            name='varient',
        ),
        migrations.CreateModel(
            name='ProductVariants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghi1234567', length=10, max_length=20, prefix='', unique=True)),
                ('size', models.CharField(choices=[('s', 'S'), ('m', 'M'), ('l', 'L')], max_length=1)),
                ('stock_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='app.product')),
            ],
            options={
                'verbose_name_plural': 'Product variants',
            },
        ),
        migrations.DeleteModel(
            name='ProductVarients',
        ),
        migrations.DeleteModel(
            name='SizeStockCount',
        ),
    ]
