# Generated by Django 5.0 on 2024-02-18 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_sizestockcount_varient_productvariants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='image',
            field=models.ImageField(default=datetime.datetime(2024, 2, 18, 15, 50, 3, 865460, tzinfo=datetime.timezone.utc), upload_to='userimage'),
            preserve_default=False,
        ),
    ]
