# Generated by Django 5.0 on 2024-02-20 10:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='care',
            field=models.CharField(default='machinewash', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='collar',
            field=models.CharField(default='collarles', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric',
            field=models.CharField(default='oversized', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='fit',
            field=models.CharField(default='oversized', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='sleeve',
            field=models.CharField(default='full sleeve', max_length=100),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, null=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Address',
            },
        ),
    ]
