# Generated by Django 5.0 on 2024-02-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_category_date_product_care_product_collar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address',
            new_name='house',
        ),
        migrations.AddField(
            model_name='address',
            name='landmark',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='pincode',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='town',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='fabric',
            field=models.CharField(default='cotton', max_length=100),
        ),
    ]
