# Generated by Django 5.0 on 2024-02-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_address_address_house_address_landmark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.IntegerField(max_length=9, null=True),
        ),
    ]
