# Generated by Django 5.0 on 2024-02-20 12:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_address_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
