# Generated by Django 5.0 on 2024-02-20 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_address_pincode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
