# Generated by Django 5.0 on 2024-02-23 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_animecharacter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='anime',
        ),
        migrations.AddField(
            model_name='product',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='character', to='app.animecharacter'),
        ),
    ]
