# Generated by Django 5.0 on 2024-02-23 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_product_anime_product_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='anime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.categoryanime'),
        ),
    ]
