name: Build and deploy Python app to Azure Web App - Animwear

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write   # ✅ Required for azure/login federated token
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: wkproject/project
        run: |
          python -m venv antenv
          source antenv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3E90CE24B4964B0EBDD8D390A11B649F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F1EF5B290DDF4BED82CB35C59D1B6AD9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_140E53876BA043528E2CFE033F4D3E6A }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Animwear'
          slot-name: 'Production'
          package: 'wkproject/project'
